---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: cert-manager
spec:
  chart: cert-manager
  targetNamespace: cert-manager
  version: v1.8.1
  repo: https://charts.jetstack.io
  valuesContent: |-
    installCRDs: true
