---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: cert-manager
  labels:
    chaosengine/cluster.stage: critical
spec:
  chart: cert-manager
  targetNamespace: cert-manager
  version: v1.8.1
  repo: https://charts.jetstack.io
  bootstrap: true
  valuesContent: |-
    installCRDs: true
