---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph

helmCharts:
  - name: rook-ceph-cluster
    releaseName: rook-ceph-cluster
    namespace: rook-ceph
    version: v1.9.8
    repo: https://charts.rook.io/release
    valuesFile: values.yaml

resources:
  - storage-macvlan-whereabouts.yaml
  - rook-ceph-dashboard-password-sealedsecret.yaml
