---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: storage-macvlan-whereabouts
  namespace: rook-ceph
spec:
  config: '{
            "name": "storage-macvlan-whereabouts",
            "type": "macvlan",
            "master": "eth1",
            "ipam": {
                "type": "whereabouts",
                "range": "192.168.50.0/24",
                "exclude": [
                  "192.168.50.0/28",
                  "192.168.50.52/32",
                  "192.168.50.238/32",
                  "192.168.50.254/32"
                ]
            }
        }'
