---
# referenced from:
# argocd-apps/cluster-workloads/monitoring/templates/kube-prom-stack.yaml
prometheus:
  admissionWebhooks:
    enabled: false
    certManager:
      enabled: true
  prometheusSpec:
    resources:
      requests:
        memory: 400Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: replicated-r2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
