---
# https://github.com/kubernetes-sigs/kustomize/issues/4354#issuecomment-1002391377
apiVersion: builtin
kind: ConfigMapGenerator
behavior: merge
metadata:
  name: argocd-cm
literals:
  - "kustomize.buildOptions=--enable-helm"
files:
  # Required for App-of-apps and sync-waves
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#argocd-app
  - resource.customizations.health.argoproj.io_Application
  # https://github.com/cilium/cilium/issues/17349#issue-991502190
  - resource.exclusions
