---
# https://github.com/kubernetes-sigs/kustomize/issues/4354#issuecomment-1002391377
apiVersion: builtin
kind: ConfigMapGenerator
behavior: merge
metadata:
  name: argocd-cm
literals:
  - "kustomize.buildOptions=--enable-helm"
files:
  - resource.customizations.health.argoproj.io_Application
  - resource.exclusions
