---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - argocd-helmchart.yaml
  - argocd-cm.yaml
  - ingressroute.yaml

commonAnnotations:
  chaosengine/version: v0.1
