---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

helmCharts:
  - name: argo-cd
    releaseName: argocd
    namespace: argocd
    repo: https://argoproj.github.io/argo-helm
    version: v4.9.4
    includeCRDs: true
    valuesInline:
      server:
        extraArgs:
          - --insecure  # use TLS on IngressRoute

generators:
  - argocd-cm.yaml

resources:
  - ingressroute.yaml
  - namespace.yaml

commonAnnotations:
  chaosengine/version: v0.1
