---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

helmCharts:
  - name: argo-cd
    namespace: argocd
    releaseName: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: v4.9.4
    includeCRDs: true
    valuesInline:
      server:
        extraArgs:
          - --insecure  # use TLS on IngressRoute

generators:
  - argocd-cm.yaml

resources:
  - ingressroute.yaml

commonAnnotations:
  chaosengine/version: v0.1
