# yamllint disable-file
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: {{ .Values.spec.source.pathPrefix }}/infra
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: infra
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
