# yamllint disable-file
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operators
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: cluster-workloads/operators
    targetRevision: {{ .Values.spec.source.targetRevision }}
    directory:
      recurse: true
  destination:
    namespace: operators
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
