---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
# https://rancher.com/docs/k3s/latest/en/helm/
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: longhorn
  labels:
    chaosengine/cluster.stage: critical
spec:
  chart: longhorn
  repo: https://charts.longhorn.io
  targetNamespace: longhorn-system
  bootstrap: true
  version: v1.3.0   # https://github.com/longhorn/charts/releases
  # https://github.com/longhorn/charts/blob/master/charts/longhorn/values.yaml
  valuesContent: |-
    ingress:
      enabled: true
      host: "longhorn.s.chaosengine.net"
      tls: true
      tlsSecret: "" # must be set if tls:true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares:
          kube-system-traefik-basic-auth@kubernetescrd
    defaultSettings:
      backupTarget: "nfs://192.168.40.52:/volume2/longhorn-backup"
