# https://longhorn.io/docs/1.3.0/monitoring/prometheus-and-grafana-setup/#install-and-configure-prometheus-server
# https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/#alerting-rules
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: longhorn
    role: alert-rules
  name: monitoring-prometheus-longhorn-rules
  namespace: kube-system
spec:
  groups:
    - name: longhorn.rules
      rules:
        - alert: LonghornVolumeUsageCritical
          annotations:
            description: Longhorn volume {{$labels.volume}} on {{$labels.node}}
              is at {{$value}}% used for more than 5 minutes.
            summary: Longhorn volume capacity is over 90% used.
          expr: 100
            * (longhorn_volume_usage_bytes / longhorn_volume_capacity_bytes)
            > 90
          for: 5m
          labels:
            issue: Longhorn volume {{$labels.volume}} usage on {{$labels.node}}
              is critical.
            severity: critical
