# https://longhorn.io/docs/1.3.0/monitoring/prometheus-and-grafana-setup/#install-longhorn-servicemonitor
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-longhorn
  namespace: kube-system
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  namespaceSelector:
    matchNames:
      - longhorn-system
  endpoints:
    - port: manager
