# https://longhorn.io/docs/1.3.0/high-availability/auto-balance-replicas/#set-individual-volumes-to-auto-balance-replicas-using-a-storageclass
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: replicated-r3
  namespace: longhorn-system
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  replicaAutoBalance: "least-effort"
  dataLocality: "best-effort"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""

#  diskSelector: "ssd,fast"
#  nodeSelector: "storage,fast"
#  recurringJobSelector: '[
#   {
#     "name":"snap",
#     "isGroup":true,
#   },
#   {
#     "name":"backup",
#     "isGroup":false,
#   }
#  ]'
