apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-vip-ds
    spec:
      containers:
      - args:
        - start
        # only used for Raft?
        #- --localPeer
        #- "${spec.nodeName}:${status.hostIP}:10000"
        #- --remotePeer
        #- k3os-002:192.168.136.146:10000,k3os-003:192.168.136.153:10000
        - --lbBindToVip
        - --lbName
        - kube-api
        - --lbPort
        - "6443"
        - --lbBackends
        - 192.168.136.136:6443,192.168.136.146:6443,192.168.136.153:6443
        env:
        - name: vip_arp
          value: "true"
        - name: vip_interface
          value: eth0
        - name: vip_address
          value: 192.168.136.249
        - name: vip_leaderelection
          value: "true"
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        #- name: vip_configmap
        #  value: ""
        # v0.1.9 was returning VIP octets reversed in gARP
        image: plndr/kube-vip:0.1.8
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_TIME
        volumeMounts:
        - mountPath: /etc/kubernetes/admin.conf
          name: kubeconfig
        - mountPath: /etc/ssl/certs
          name: ca-certs
          readOnly: true
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - hostPath:
          path: /etc/rancher/k3s/k3s.yaml
        name: kubeconfig
      - hostPath:
          path: /etc/ssl/certs
        name: ca-certs
  updateStrategy: {}
