# yamllint disable
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-critical-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: {{ .Values.spec.source.pathPrefix }}/cluster-critical
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
