# yamllint disable-file
# https://blog.ediri.io/kube-prometheus-stack-and-argocd-23-how-to-remove-a-workaround
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom-stack-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "41"  # must be before kube-prom-stack.yaml
spec:
  source:
    repoURL: https://github.com/prometheus-commuity/helm-charts.git
    path: charts/kube-prom-stack/crds/
    targetRevision: kube-prometheus-stack-{{ .Values.kubePromStackVersion }}
    directory:
      recurse: true
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    syncOptions:
      - Replace=true
    automated:
      prune: true
      selfHeal: true
