# yamllint disable-file
# https://blog.ediri.io/kube-prometheus-stack-and-argocd-23-how-to-remove-a-workaround
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom-stack-chart
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "42"  # must be after kube-prom-stack-crds.yaml
spec:
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: {{ .Values.kubePromStackVersion }}
    helm:
      skipCrds: true
      values: |-
        prometheus:
          admissionWebhooks:
            enabled: false
            certManager:
              enabled: true
          prometheusSpec:
            resources:
              requests:
                memory: 400Mi
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: replicated-r2
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 50Gi
    chart: kube-prometheus-stack
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

