---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

helmCharts:
  - name: plex
    releaseName: plex
    namespace: media
    repo: https://k8s-at-home.com/charts/
    version: "6.3.3"
    valuesFile: values.yaml

resources:
  - nas-media-pvc.yaml
  - plex-transcode-pvc.yaml
  - plex-config-pvc.yaml
  - ingressroute.yaml

commonAnnotations:
  chaosengine/version: v0.1
