---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-media-pv
  namespace: media
spec:
  storageClassName: "nfs-nas-media"
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.50.52
    path: "/volume1/media"
    readOnly: false
  mountOptions:
    - tcp
    - intr
    - hard
    - relatime
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-media-pvc
  namespace: media
spec:
  storageClassName: "nfs-nas-media"
  volumeName: nas-media-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
