---
# yamllint disable rule:line-length
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

# image:
#  # -- image repository
#  repository: jacobalberty/unifi
#  tag:
#  # -- image pull policy
#  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [image documentation](https://github.com/jacobalberty/unifi-docker#environment-variables).
env:
  TZ: America/Los_Angeles
  RUNAS_UID0: "false"
  BIND_PRIV: "false"
  UNIFI_UID: "999"
  UNIFI_GID: "999"
  # -- Java Virtual Machine (JVM) initial, and minimum, heap size
  # Unset value means there is no lower limit
  JVM_INIT_HEAP_SIZE:
  # -- Java Virtual Machine (JVM) maximum heap size
  # For larger installations a larger value is recommended.
  # For memory constrained system this value can be lowered.
  JVM_MAX_HEAP_SIZE: 1024M

podSecurityContext:
  fsGroup: 999

service:
  main:
    ports:
      # -- Configure Web interface + API port
      http:
        port: 8443
        protocol: HTTPS
      # -- Configure Controller port used for device command/control
      controller:
        enabled: true
        port: 8080
        protocol: TCP
      # -- Configure Captive Portal HTTP port
      portal-http:
        enabled: false
        port: 8880
        protocol: HTTP
      # -- Configure Captive Portal HTTPS port
      portal-https:
        enabled: false
        port: 8843
        protocol: HTTPS
      # -- Configure Speedtest port (used for UniFi mobile speed test)
      speedtest:
        enabled: true
        port: 6789
        protocol: TCP
      # -- Configure STUN port
      stun:
        enabled: true
        port: 3478
        protocol: UDP
      # -- Configure remote syslog port
      syslog:
        enabled: true
        port: 5514
        protocol: UDP
      # -- Configure device discovery port
      discovery:
        enabled: true
        port: 10001
        protocol: UDP

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: false
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares:
        kube-system-secured@kubernetescrd
    hosts:
      - host: unifi.s.chaosengine.net
        paths:
          - path: /

# -- Configure persistence settings for the chart under this key.
persistence:
  data:
    enabled: true
    mountPath: /unifi
    storageClass: "replicated-r2-v2"
    accessMode: ReadWriteOnce
    size: 5Gi

# -- Enable and configure mongodb database subchart under this key.
#    For more options see [mongodb chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/mongodb)
mongodb:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  persistence:
    enabled: true
    storageClass: "replicated-r2-v2"
    size: 5Gi
  metrics:
    enabled: true
