---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: usb-ups
spec:
  rules:
    - name: "Cyberpower UPS"
      labels:
        "usb-ups": "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            # 0764:0501
            vendor: {op: In, value: ["0764"]}
            class: {op: In, value: ["0501"]}
