---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - sealed-secrets.yaml
  - cert-manager.yaml
  - longhorn-system.yaml
  - traefik.yaml
  - argocd.yaml
