---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "longhorn-system"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/deekue/homelab"
    path: cluster-critical/longhorn-system
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
