---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "nfs"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/deekue/homelab"
    path: cluster-critical/argocd-apps/nfs
    targetRevision: master
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
