---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

HelmChartInflationGenerator:
  - chartName: kube-prometheus-stack
    chartRepoUrl: https://prometheus-community.github.io/helm-charts
    chartVersion: "33.1.0"
    releaseName: monitoring
    releaseNamespace: kube-system
    values: values.yaml

bases:
  - crds

resources:
  - ingressroute.yaml
