---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: cert-manager
    releaseName: cert-manager
    namespace: kube-system
    version: v1.9.1
    repo: https://charts.jetstack.io
    valuesInline:
      installCRDs: false
      webhook:
        enabled: true

resources:
  - namespace.yaml
  - crds/cert-manager.crds-v1.9.1.yaml

# FIXME Warning: would violate PodSecurity "restricted:latest": unrestricted
# capabilities (container "cert-manager" must set
# securityContext.capabilities.drop=["ALL"]), seccompProfile (pod or contai
# ner "cert-manager" must set securityContext.seccompProfile.type to
# "RuntimeDefault" or "Localhost")
