---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: sealed-secrets
    releaseName: sealed-secrets
    namespace: kube-system
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: "v2.2.0"
    valuesInline:
      fullnameOverride: sealed-secrets-controller
