---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmCharts:
  - name: loki-stack
    releaseName: loki
    namespace: monitoring
    repo: https://grafana.github.io/helm-charts
    version: 2.6.5
    valuesFile: values.yaml

resources:
  - pvc.yaml
