---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: replicated-r3
  resources:
    requests:
      storage: 50Gi
