---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra

helmCharts:
  - name: kubenav
    releaseName: kubenav
    namespace: infra
    repo: https://kubenav.github.io/helm-repository
    version: "1.2.0"
    valuesFile: values.yaml
