---
kubeVersion: "1.24"  # https://github.com/kubernetes-sigs/kustomize/pull/4666
# https://raw.githubusercontent.com/kubenav/deploy/master/helm/values.yaml
ingress:
  enabled: true
  hosts:
    - host: kubenav.s.chaosengine.net
      paths:
        - /
  tls: []
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-secured@kubernetescrd
