apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-basic-auth
  namespace: kube-system
spec:
  encryptedData:
    users: AgAkr4sAiAbb9Hdv+VQ1W5pXlEgctfl6By893gGY5IsSE3oLCVqZlSjWxneB/wIWmB9HYUizkDhkE60XFstvU+E0WUPedoPKdvoFZYP+ph1t5W8z3j2E6tC/4xR9LKsm5/zM9FnBQggb6mzm29xDrR2yC7oNWWhKtNO9eSlgSzKQtom0H7rNZUF9jMcKy8UeKYfiIy0rBsl73hwqpoHRtT3SBn3UWbZthgm1/rQoiBLLgPsoVD82Sd8K6sCaDyHRkJ32o9EkNKRofBMpJr9uo+0yt0FdE3u8XoRCRCdV5e+NTDf+1rpvWhtSMtQK+vJPKDk+yLzP72rhbGb9iAm6kj/eyhP3ahq066OJ9wFVuFuXNNCcXa6L6IwFJJMRUrL/ww3iZKh7Wnd+qoIS3nftAqPp5gl7Oxg5SiT6PxoRt/bUHjEgECmUDZp+LRr/mAyK0rUSeEi62RCt+YSZfr2voMau2hrdHfpMhoi+Cq+Wd6I9PfnHlO5atcLy3oSGhAAxRBUDuECcpoSvqTzdkW9TMCpx5ZCV3Qiflxg0ip4h6w1nqD13typRsKGlBGQ+Go2w/GvH27KRJW4PU5UHiv78tb1Kwgwet1p6yNOhX/sFgQI8/NlysJE1Ku0tCWOVUy9w/PUlC6PplWS1ozmauARgoAHVuZVMmkjm80KK0IoWkf+zMrjKYukvTxpB5CUr+dqAwpmnWeEeVTSjRjT1vRK365ae1ZoZHxurVwj1bmjUnbMC/w1gEInl5ft/ir2wQJ8R
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: traefik-basic-auth
      namespace: kube-system

