# yamllint disable
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: {{ .Values.spec.source.pathPrefix }}/argocd
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
