# yamllint disable-file
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: {{ .Values.spec.source.pathPrefix }}/cilium
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
  # https://github.com/cilium/cilium/issues/17349
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: hubble-ca-cert
      jsonPointers:
      - /data/ca.crt
    - group: ""
      kind: Secret
      name: hubble-relay-client-certs
      jsonPointers:
      - /data/ca.crt
      - /data/tls.crt
      - /data/tls.key
    - group: ""
      kind: Secret
      name: hubble-server-certs
      jsonPointers:
      - /data/ca.crt
      - /data/tls.crt
      - /data/tls.key

