# yamllint disable
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-system
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: {{ .Values.spec.source.pathPrefix }}/longhorn-system
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: longhorn-system
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
