# yamllint disable-file
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: {{ .Values.spec.source.pathPrefix }}/multus
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
