# yamllint disable-file
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: {{ .Values.spec.source.pathPrefix }}/rook-ceph
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: rook-ceph
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    automated:
      prune: false
    syncOptions:
      - CreateNamespace=true
