# https://raw.githubusercontent.com/argoproj/argocd-example-apps/master/apps/values.yaml
---
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/deekue/homelab
    pathPrefix: argocd-apps/cluster-workloads
    targetRevision: HEAD
