---
# https://rancher.com/docs/k3s/latest/en/helm/
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: node-feature-discovery
spec:
  chart: node-feature-discovery
  targetNamespace: infra
  version: 2.0.0
  repo: https://k8s-at-home.com/charts/
  # jobImage: raspbernetes/node-feature-discovery:v0.6.0
  valuesContent: |-
    sources:
      # - cpu
      - custom
      # - iommu
      # - kernel
      # - local
      # - memory
      # - network
      - pci
      # - storage
      # - system
      - usb
    # node-feature-discovery configuration
    # see https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/nfd-worker.conf.example
    config: |
      sources:
        usb:
          deviceClassWhitelist:
            - "02"
            - "0e"
            - "ef"
            - "fe"
            - "ff"
          deviceLabelFields:
            - "class"
            - "vendor"
            - "device"
        custom:
          - name: "intel-gpu"
            matchOn:
              - pciId:
                  class: ["0300"]
                  vendor: ["8086"]
#    master:
#      replicaCount: 1
#      tolerations:
#        - key: "node-role.kubernetes.io/master"
#          operator: "Equal"
#          value: ""
#          effect: "NoSchedule"
#        - key: arm
#          operator: Exists
#    worker:
#      tolerations:
#        - key: arm
#          operator: Exists
