# https://raw.githubusercontent.com/argoproj/argocd-example-apps/master/apps/values.yaml
---
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  source:
    repoURL: https://github.com/deekue/homelab
    pathPrefix: cluster-workloads/infra
    targetRevision: HEAD
