---
cluster:
  name: "k8s"
  id: "1"
k8sServiceHost: 192.168.40.10
k8sServicePort: 6443
rollOutCiliumPods: true
bpf:
  masquerade: true
  hostRouting: false
cni:
  confPath: /etc/cni/net.d
  binPath: /opt/cni/bin
ipam:
  mode: "kubernetes"
ipMasqAgent:
  enabled: true
kubeProxyReplacement: "strict"
egressGateway:
  enabled: true
securityContext:  # agents
  privileged: true
operator:
  rollOutPods: true
containerRuntime:
  integration: containerd
# Native routing
tunnel: disabled
ipv4NativeRoutingCIDR: 10.244.0.0/16
autoDirectNodeRoutes: true
endpointRoutes:
  enabled: true
localRedirectPolicy: true
loadBalancer:
  algorithm: "maglev"
  mode: "dsr"
# end of common features
hubble:
  enabled: true
  serviceMonitor:
    enabled: true
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
bgp:
  enabled: true
  announce:
    loadbalancerIP: true
    podCIDR: true
