---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: traefik
    releaseName: traefik
    namespace: kube-system
    repo: https://helm.traefik.io/traefik
    version: "v10.24.0"
    includeCRDs: true
    valuesInline:
      deployment:
        enabled: true
        kind: Deployment
        replicas: 2
      logs:
        access:
          enabled: true
          format: json
      # general:
      #   format: json
      #   level: DEBUG
      ports:
        web:
          redirectTo: websecure
        websecure:
          tls:
            enabled: true
      ingressRoute:
        dashboard:
          enabled: true
      dashboard:
        domain: "traefik.s.chaosengine.net"
      globalArguments:
        - "--serversTransport.insecureSkipVerify=true"
      providers:
        kubernetesCRD:
          allowExternalNameServices: true

resources:
  - traefik-basic-auth-sealedsecret.yaml
  - wildcard-s-chaosengine-net-tls-sealedsecret.yaml
  - wildcard.s.chaosengine.net.yaml
  - tls-config.yaml
  - middleware.yaml
  - ingressroute.yaml
