# https://github.com/k3s-io/k3s/issues/2893#issuecomment-773654746
# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    logs:
      access:
        enabled: true
    ports:
      web:
        redirectTo: websecure
    dashboard:
      domain: "traefik.s.chaosengine.net"
