# https://rancher.com/docs/k3s/latest/en/helm/
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: longhorn
spec:
  chart: longhorn
  repo: https://charts.longhorn.io
  targetNamespace: longhorn-system
  version: v1.3.0   # https://github.com/longhorn/charts/releases
  # https://github.com/longhorn/charts/blob/master/charts/longhorn/values.yaml
  valuesContent: |-
    ingress:
      enabled: true
      host: "longhorn.s.chaosengine.net"
      #ingressClassName:
      tls: true
      tlsSecret: "" # must be set if tls:true

#    csi:
#     kubeletRootDir: ""
#    defaultSettings:
#     backupTarget: "nfs://metis/longhorn-backup"
#     backupTargetCredentialSecret: ""
